# NOTE: if this is false, you'll need to run :PluginInstall in vim to
# install all plugins
nvim_install_plugins: yes
nvim_clean_plugins: yes
nvim_update_plugins: no

# Only used on Mac machines. Ignored on other platforms
nvim_install_mac: yes
