- name: Install pyenv package requirements
  apt:
    name: [
        'make',
        'build-essential',
        'libssl-dev',
        'zlib1g-dev',
        'libbz2-dev',
        'libffi-dev',
        'libreadline-dev',
        'libsqlite3-dev',
        'wget',
        'curl',
        'llvm',
        'libncurses5-dev',
        'libncursesw5-dev',
        'xz-utils',
        'tk-dev',
        'python-pip',
        'python3-pip',
        'python3-setuptools'
    ]
    state: present
  become: true

- name: Install pyenv from source
  shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  args:
    warn: false
    creates: "{{ '~/.pyenv/' | expanduser }}"

- name: Add symlink to /usr/bin
  file:
    src: "{{ '~/.pyenv/bin/pyenv' | expanduser }}"
    dest: /usr/bin/pyenv
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link
    mode: "o+x"
  become: true

