
# Pyenv Installation
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

# Install python versions

- name: Install python versions
  command: pyenv install {{item}}
  args:
    creates: "{{ '~/.pyenv/versions/' + item | expanduser }}"
  with_items: [
    "2.7.15",
    "3.6.5",
    "3.7.1"
  ]

