- name: Install fzf with Homebrew
  homebrew: name=fzf state=latest
  when: ansible_os_family == "Darwin"

- name: Install fzf with git
  shell: "{{ 'git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --all' | expanduser }}"
  when: ansible_os_family == "Debian"
  args:
    creates: "{{ '~/.fzf' | expanduser }}"


- name: Add symlink to /usr/bin
  when: ansible_os_family == "Debian"
  file:
    src: "{{ '~/.fzf/bin/fzf' | expanduser }}"
    dest: /usr/bin/fzf
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link
    mode: "o+x"
  become: true
